<?php
if (! function_exists('getFormulaScore')) {
    function getFormulaScore($readingNumber, $listeningNumber, $totalQuestion, $option) {
        if ($option == \App\Models\Test::IS_FORMULA_SCORE_TRUE) {
            $score = getReadingScore($readingNumber) + getListeningScore($listeningNumber);
        } else {
            $score = round(($readingNumber + $listeningNumber) * 100 / $totalQuestion);
        }

        return $score;
    }
}

if (! function_exists('getReadingScore')) {
    function getReadingScore($readingNumber)
    {
        switch ($readingNumber) {
            case 0:
            case 1:
            case 2:
            case 3:
            case 4:
            case 5:
            case 6:
            case 7:
            case 8:
            case 9:
                return 5;
            case 10:
                return 10;
            case 11:
                return 15;
            case 12:
                return 20;
            case 13:
                return 25;
            case 14:
                return 30;
            case 15:
                return 35;
            case 16:
                return 40;
            case 17:
                return 45;
            case 18:
                return 50;
            case 19:
                return 55;
            case 20:
                return 60;
            case 21:
                return 65;
            case 22:
                return 70;
            case 23:
                return 75;
            case 24:
                return 80;
            case 25:
                return 90;
            case 26:
                return 95;
            case 27:
                return 100;
            case 28:
                return 110;
            case 29:
                return 115;
            case 30:
                return 120;
            case 31:
                return 125;
            case 32:
                return 130;
            case 33:
                return 135;
            case 34:
                return 140;
            case 35:
                return 145;
            case 36:
                return 150;
            case 37:
                return 155;
            case 38:
                return 160;
            case 39:
                return 170;
            case 40:
                return 175;
            case 41:
                return 180;
            case 42:
                return 185;
            case 43:
                return 195;
            case 44:
                return 200;
            case 45:
                return 205;
            case 46:
                return 210;
            case 47:
                return 220;
            case 48:
                return 225;
            case 49:
                return 230;
            case 50:
                return 235;
            case 51:
                return 240;
            case 52:
                return 250;
            case 53:
                return 255;
            case 54:
                return 260;
            case 55:
                return 270;
            case 56:
                return 275;
            case 57:
                return 280;
            case 58:
                return 285;
            case 59:
                return 290;
            case 60:
                return 295;
            case 61:
                return 300;
            case 62:
                return 305;
            case 63:
                return 310;
            case 64:
                return 320;
            case 65:
                return 325;
            case 66:
                return 330;
            case 67:
                return 335;
            case 68:
                return 340;
            case 69:
                return 345;
            case 70:
                return 350;
            case 71:
                return 355;
            case 72:
                return 360;
            case 73:
                return 365;
            case 74:
                return 370;
            case 75:
                return 375;
            case 76:
                return 380;
            case 77:
                return 385;
            case 78:
                return 390;
            case 79:
                return 395;
            case 80:
                return 400;
            case 81:
            case 82:
                return 405;
            case 83:
                return 410;
            case 84:
                return 415;
            case 85:
                return 420;
            case 86:
                return 425;
            case 87:
                return 430;
            case 88:
                return 435;
            case 89:
                return 445;
            case 90:
                return 450;
            case 91:
                return 455;
            case 92:
                return 465;
            case 93:
                return 470;
            case 94:
                return 480;
            case 95:
                return 485;
            case 96:
                return 490;
            case 97:
            case 98:
            case 99:
            case 100:
                return 495;
            default:
                return 5;
        }
    }
}

if (! function_exists('getListeningScore')) {
    function getListeningScore($listeningNumber)
    {
        switch ($listeningNumber) {
            case 0:
            case 1:
            case 2:
            case 3:
            case 4:
            case 5:
            case 6:
                return 5;
            case 7:
                return 10;
            case 8:
                return 15;
            case 9:
                return 20;
            case 10:
                return 25;
            case 11:
                return 30;
            case 12:
                return 35;
            case 13:
                return 40;
            case 14:
                return 45;
            case 15:
                return 50;
            case 16:
                return 55;
            case 17:
                return 60;
            case 18:
                return 65;
            case 19:
                return 70;
            case 20:
                return 75;
            case 21:
                return 80;
            case 22:
                return 85;
            case 23:
                return 90;
            case 24:
                return 95;
            case 25:
                return 100;
            case 26:
                return 105;
            case 27:
                return 110;
            case 28:
                return 115;
            case 29:
                return 120;
            case 30:
                return 125;
            case 31:
                return 135;
            case 32:
                return 140;
            case 33:
                return 145;
            case 34:
                return 150;
            case 35:
                return 155;
            case 36:
                return 160;
            case 37:
                return 165;
            case 38:
                return 170;
            case 39:
                return 180;
            case 40:
                return 185;
            case 41:
                return 190;
            case 42:
                return 195;
            case 43:
                return 200;
            case 44:
                return 210;
            case 45:
                return 220;
            case 46:
                return 225;
            case 47:
                return 230;
            case 48:
                return 235;
            case 49:
                return 240;
            case 50:
                return 245;
            case 51:
                return 250;
            case 52:
                return 255;
            case 53:
                return 260;
            case 54:
                return 270;
            case 55:
                return 275;
            case 56:
                return 280;
            case 57:
                return 285;
            case 58:
                return 295;
            case 59:
                return 300;
            case 60:
                return 305;
            case 61:
                return 310;
            case 62:
                return 315;
            case 63:
                return 320;
            case 64:
                return 325;
            case 65:
                return 330;
            case 66:
                return 335;
            case 67:
                return 340;
            case 68:
                return 345;
            case 69:
                return 350;
            case 70:
                return 360;
            case 71:
                return 365;
            case 72:
                return 370;
            case 73:
                return 375;
            case 74:
                return 380;
            case 75:
                return 390;
            case 76:
                return 395;
            case 77:
                return 400;
            case 78:
                return 405;
            case 79:
                return 410;
            case 80:
                return 420;
            case 81:
                return 425;
            case 82:
                return 430;
            case 83:
                return 435;
            case 84:
                return 440;
            case 85:
                return 450;
            case 86:
                return 455;
            case 87:
                return 460;
            case 88:
                return 470;
            case 89:
                return 475;
            case 90:
                return 480;
            case 91:
                return 485;
            case 92:
                return 490;
            case 93:
            case 94:
            case 95:
            case 96:
            case 97:
            case 98:
            case 99:
            case 100:
                return 495;
            default:
                return 5;
        }
    }
}
